ndk

diff --git a/config b/config
--- a/config
+++ b/config
@@ -1,18 +1,18 @@
-#if test -n "$ngx_module_link"; then
-#    if test -n "$NDK_SRCS"; then
-#        echo "found ngx_devel_kit for ngx_encrypted_session; looks good."
-#    else
-#        echo "error: ngx_devel_kit is required to build ngx_encrypted_session; please put it before ngx_encrypted_session." 1>&2
-#        exit 1
-#    fi
-#else
-#    if echo $HTTP_MODULES | grep " ndk_http_module" > /dev/null; then
-#        echo "found ngx_devel_kit for ngx_encrypted_session; looks good."
-#    else
-#        echo "error: ngx_devel_kit is required to build ngx_encrypted_session; please put it before ngx_encrypted_session." 1>&2
-#        exit 1
-#    fi
-#fi
+if test -n "$ngx_module_link"; then
+    if test -n "$NDK_SRCS"; then
+        echo "found ngx_devel_kit for ngx_encrypted_session; looks good."
+    else
+        echo "error: ngx_devel_kit is required to build ngx_encrypted_session; please put it before ngx_encrypted_session." 1>&2
+        exit 1
+    fi
+else
+    if echo $HTTP_MODULES | grep " ndk_http_module" > /dev/null; then
+        echo "found ngx_devel_kit for ngx_encrypted_session; looks good."
+    else
+        echo "error: ngx_devel_kit is required to build ngx_encrypted_session; please put it before ngx_encrypted_session." 1>&2
+        exit 1
+    fi
+fi
 
 ngx_addon_name=ngx_http_encrypted_session_module
 
@@ -41,3 +41,5 @@ else
     NGX_ADDON_DEPS="$NGX_ADDON_DEPS $HTTP_ENCRYPTED_SESSION_DEPS"
 fi
 
+CFLAGS="$CFLAGS -DNDK_SET_VAR"
+#CORE_LIBS="$CORE_LIBS -lssl"
